eval "$(/opt/homebrew/bin/brew shellenv)"
# efw - 05/16/24
echo "loaded .bashrc- $(date)" >> startup.txt

for DOTFILE in `find /Users/erikweibust/.dotfiles/system`
do
   [ -f $DOTFILE ] && source $DOTFILE
done

for DOTFILE in `find /Users/erikweibust/.dotfiles/.secret`
do
   [ -f $DOTFILE ] && source $DOTFILE
done

# used this site to update to latest version of Bash
# https://smallsharpsoftwaretools.com/tutorials/use_modern_bash_on_macos/

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/erikweibust/.sdkman"
[[ -s "/Users/erikweibust/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/erikweibust/.sdkman/bin/sdkman-init.sh"
