eval "$(/opt/homebrew/bin/brew shellenv)"
# efw - 05/16/24
echo "loaded .bashrc - $(date)" >> ~/.startup.txt

# changing from hard-coded dir to variables but not testing. revert to this format if errors
#for DOTFILE in `find /Users/username-was-mine/.dotfiles/system`

for DOTFILE in `find $HOME/.dotfiles/system`
do
   [ -f $DOTFILE ] && source $DOTFILE
done

for DOTFILE in `find $HOME/.dotfiles/.secret`
do
   [ -f $DOTFILE ] && source $DOTFILE
done

# used this site to update to latest version of Bash
# https://smallsharpsoftwaretools.com/tutorials/use_modern_bash_on_macos/

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
